import type { EquipmentCategory } from '../../types'

/**
 * แค็ตตาล็อกผลิตภัณฑ์สำหรับ autocomplete ในฟอร์มสต็อกอุปกรณ์
 *
 * ⚠️ รายการ port มาจากความรู้ทั่วไปของรุ่นนั้น ไม่ได้ดึงจาก spec sheet ทางการ
 * ใช้เป็นค่าตั้งต้นให้แก้ต่อ — บางรุ่นย่อย/บาง revision มี port ต่างจากนี้
 * เพิ่มยี่ห้ออื่นได้ด้วยการเพิ่มไฟล์ใน catalog/ แล้วรวมใน index.ts
 */
export interface CatalogProduct {
  brand: string
  name: string                 // ชื่อรุ่นเต็ม (ใช้เป็นชื่ออุปกรณ์ตั้งต้น)
  model?: string               // ถ้าไม่ระบุ = name
  category: EquipmentCategory
  aliases?: string[]           // คำค้นเพิ่ม เช่น "bmd", "constellation"
  inputs?: string[]
  outputs?: string[]
  ios?: string[]
  price?: number               // ราคาโดยประมาณ (บาท/ชิ้น) — เติมจาก prices.ts ตอนรวมใน index.ts
  priceNote?: string           // เช่น "ต่อข้าง — คู่ละ ~17,900"
}

const B = 'Blackmagic Design'
const seq = (prefix: string, n: number, from = 1) => Array.from({ length: n }, (_, i) => `${prefix} ${from + i}`)

export const BLACKMAGIC_PRODUCTS: CatalogProduct[] = [
  // ── ATEM switchers ──────────────────────────────────────────────────────
  { brand: B, name: 'ATEM Mini', category: 'switcher', aliases: ['bmd'],
    inputs: [...seq('HDMI IN', 4), 'MIC 1', 'MIC 2'], outputs: ['HDMI OUT'], ios: ['USB-C'] },
  { brand: B, name: 'ATEM Mini Pro', category: 'switcher', aliases: ['bmd'],
    inputs: [...seq('HDMI IN', 4), 'MIC 1', 'MIC 2'], outputs: ['HDMI OUT'], ios: ['USB-C', 'ETHERNET'] },
  { brand: B, name: 'ATEM Mini Pro ISO', category: 'switcher', aliases: ['bmd'],
    inputs: [...seq('HDMI IN', 4), 'MIC 1', 'MIC 2'], outputs: ['HDMI OUT'], ios: ['USB-C', 'ETHERNET'] },
  { brand: B, name: 'ATEM Mini Extreme', category: 'switcher', aliases: ['bmd'],
    inputs: [...seq('HDMI IN', 8), 'MIC 1', 'MIC 2'], outputs: ['HDMI OUT 1', 'HDMI OUT 2'], ios: ['USB-C 1', 'USB-C 2', 'ETHERNET'] },
  { brand: B, name: 'ATEM Mini Extreme ISO', category: 'switcher', aliases: ['bmd'],
    inputs: [...seq('HDMI IN', 8), 'MIC 1', 'MIC 2'], outputs: ['HDMI OUT 1', 'HDMI OUT 2'], ios: ['USB-C 1', 'USB-C 2', 'ETHERNET'] },
  { brand: B, name: 'ATEM SDI', category: 'switcher', aliases: ['bmd'],
    inputs: [...seq('SDI IN', 4), 'MIC 1', 'MIC 2'], outputs: ['SDI OUT'], ios: ['USB-C', 'ETHERNET'] },
  { brand: B, name: 'ATEM SDI Pro ISO', category: 'switcher', aliases: ['bmd'],
    inputs: [...seq('SDI IN', 4), 'MIC 1', 'MIC 2'], outputs: ['SDI OUT'], ios: ['USB-C', 'ETHERNET'] },
  { brand: B, name: 'ATEM SDI Extreme ISO', category: 'switcher', aliases: ['bmd'],
    inputs: [...seq('SDI IN', 8), 'MIC 1', 'MIC 2'], outputs: ['SDI OUT 1', 'SDI OUT 2'], ios: ['USB-C 1', 'USB-C 2', 'ETHERNET'] },
  { brand: B, name: 'ATEM Television Studio HD8', category: 'switcher', aliases: ['bmd', 'tvs'],
    inputs: [...seq('SDI IN', 8), 'MIC 1', 'MIC 2'], outputs: ['PGM SDI', 'AUX 1', 'AUX 2', 'MULTIVIEW'], ios: ['USB-C', 'ETHERNET'] },
  { brand: B, name: 'ATEM Television Studio HD8 ISO', category: 'switcher', aliases: ['bmd', 'tvs'],
    inputs: [...seq('SDI IN', 8), 'MIC 1', 'MIC 2'], outputs: ['PGM SDI', 'AUX 1', 'AUX 2', 'MULTIVIEW'], ios: ['USB-C', 'ETHERNET'] },
  { brand: B, name: 'ATEM Television Studio 4K8', category: 'switcher', aliases: ['bmd', 'tvs'],
    inputs: seq('12G-SDI IN', 8), outputs: [...seq('12G-SDI OUT', 8), 'MULTIVIEW'], ios: ['USB-C', 'ETHERNET'] },
  { brand: B, name: 'ATEM 1 M/E Constellation HD', category: 'switcher', aliases: ['bmd', 'constellation'],
    inputs: seq('SDI IN', 10), outputs: [...seq('SDI OUT', 6), 'MULTIVIEW'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 2 M/E Constellation HD', category: 'switcher', aliases: ['bmd', 'constellation'],
    inputs: seq('SDI IN', 20), outputs: [...seq('SDI OUT', 12), 'MULTIVIEW 1', 'MULTIVIEW 2'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 4 M/E Constellation HD', category: 'switcher', aliases: ['bmd', 'constellation'],
    inputs: seq('SDI IN', 40), outputs: [...seq('SDI OUT', 24), 'MULTIVIEW 1', 'MULTIVIEW 2', 'MULTIVIEW 3', 'MULTIVIEW 4'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 1 M/E Constellation 4K', category: 'switcher', aliases: ['bmd', 'constellation'],
    inputs: seq('12G-SDI IN', 10), outputs: [...seq('12G-SDI OUT', 6), 'MULTIVIEW'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 2 M/E Constellation 4K', category: 'switcher', aliases: ['bmd', 'constellation'],
    inputs: seq('12G-SDI IN', 20), outputs: [...seq('12G-SDI OUT', 12), 'MULTIVIEW 1', 'MULTIVIEW 2'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 4 M/E Constellation 4K', category: 'switcher', aliases: ['bmd', 'constellation'],
    inputs: seq('12G-SDI IN', 40), outputs: [...seq('12G-SDI OUT', 24), 'MULTIVIEW 1', 'MULTIVIEW 2', 'MULTIVIEW 3', 'MULTIVIEW 4'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM Constellation 8K', category: 'switcher', aliases: ['bmd', 'constellation'],
    inputs: seq('12G-SDI IN', 40), outputs: [...seq('12G-SDI OUT', 24), 'MULTIVIEW 1', 'MULTIVIEW 2'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 1 M/E Production Studio 4K', category: 'switcher', aliases: ['bmd'],
    inputs: seq('IN', 10), outputs: ['PGM SDI', 'PGM HDMI', 'AUX 1', 'AUX 2', 'AUX 3', 'MULTIVIEW'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 2 M/E Production Studio 4K', category: 'switcher', aliases: ['bmd'],
    inputs: seq('IN', 20), outputs: ['PGM SDI', 'PGM HDMI', ...seq('AUX', 6), 'MULTIVIEW 1', 'MULTIVIEW 2'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM Streaming Bridge', category: 'converter', aliases: ['bmd'],
    inputs: [], outputs: ['SDI OUT', 'HDMI OUT'], ios: ['ETHERNET', 'USB-C'] },
  // Broadcast Panel = รุ่นเก่าตัวเทา (ก่อน Advanced Panel) ยังใช้กับ ATEM รุ่นใหม่ได้ผ่าน Ethernet
  { brand: B, name: 'ATEM 1 M/E Broadcast Panel', category: 'switcher', aliases: ['bmd', 'panel', 'สีเทา', 'รุ่นเก่า'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 2 M/E Broadcast Panel', category: 'switcher', aliases: ['bmd', 'panel', 'สีเทา', 'รุ่นเก่า'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 2 M/E Production Switcher', category: 'switcher', aliases: ['bmd', 'รุ่นเก่า'],
    inputs: seq('IN', 16), outputs: ['PGM SDI', 'PGM HDMI', ...seq('AUX', 6), 'MULTIVIEW 1', 'MULTIVIEW 2'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 1 M/E Production Switcher', category: 'switcher', aliases: ['bmd', 'รุ่นเก่า'],
    inputs: seq('IN', 8), outputs: ['PGM SDI', 'PGM HDMI', 'AUX 1', 'AUX 2', 'AUX 3', 'MULTIVIEW'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM Television Studio', category: 'switcher', aliases: ['bmd', 'tvs', 'รุ่นเก่า'],
    inputs: ['SDI IN 1', 'SDI IN 2', 'SDI IN 3', 'SDI IN 4', 'HDMI IN 1', 'HDMI IN 2', 'HDMI IN 3', 'HDMI IN 4'], outputs: ['PGM SDI', 'PGM HDMI', 'AUX', 'MULTIVIEW'], ios: ['ETHERNET', 'USB'] },
  { brand: B, name: 'ATEM Television Studio HD', category: 'switcher', aliases: ['bmd', 'tvs'],
    inputs: ['SDI IN 1', 'SDI IN 2', 'SDI IN 3', 'SDI IN 4', 'HDMI IN 1', 'HDMI IN 2', 'HDMI IN 3', 'HDMI IN 4', 'MIC 1', 'MIC 2'], outputs: ['PGM SDI', 'PGM HDMI', 'AUX', 'MULTIVIEW'], ios: ['ETHERNET', 'USB'] },
  { brand: B, name: 'ATEM Television Studio Pro HD', category: 'switcher', aliases: ['bmd', 'tvs'],
    inputs: ['SDI IN 1', 'SDI IN 2', 'SDI IN 3', 'SDI IN 4', 'HDMI IN 1', 'HDMI IN 2', 'HDMI IN 3', 'HDMI IN 4', 'MIC 1', 'MIC 2'], outputs: ['PGM SDI', 'PGM HDMI', 'AUX', 'MULTIVIEW'], ios: ['ETHERNET', 'USB'] },
  { brand: B, name: 'ATEM Television Studio Pro 4K', category: 'switcher', aliases: ['bmd', 'tvs'],
    inputs: [...seq('12G-SDI IN', 8), 'MIC 1', 'MIC 2'], outputs: ['PGM 12G-SDI', 'AUX', 'MULTIVIEW'], ios: ['ETHERNET', 'USB'] },
  { brand: B, name: 'ATEM 1 M/E Advanced Panel 10', category: 'switcher', aliases: ['bmd', 'panel'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 1 M/E Advanced Panel 20', category: 'switcher', aliases: ['bmd', 'panel'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 2 M/E Advanced Panel 20', category: 'switcher', aliases: ['bmd', 'panel'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM 2 M/E Advanced Panel 40', category: 'switcher', aliases: ['bmd', 'panel'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM Camera Control Panel', category: 'switcher', aliases: ['bmd', 'ccu', 'panel'], ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM Micro Camera Panel', category: 'switcher', aliases: ['bmd', 'ccu', 'panel'], ios: ['ETHERNET', 'USB-C'] },
  { brand: B, name: 'ATEM Talkback Converter 4K', category: 'intercom', aliases: ['bmd'],
    inputs: seq('SDI IN', 8), outputs: seq('SDI OUT', 8), ios: ['ETHERNET'] },
  { brand: B, name: 'ATEM Microphone Converter', category: 'audio', aliases: ['bmd'],
    inputs: seq('MIC IN', 4), outputs: ['MADI OUT'], ios: ['ETHERNET', 'USB-C'] },

  // ── Cameras ─────────────────────────────────────────────────────────────
  { brand: B, name: 'Pocket Cinema Camera 4K', model: 'BMPCC 4K', category: 'camera', aliases: ['bmd', 'bmpcc'],
    outputs: ['HDMI OUT'] },
  { brand: B, name: 'Pocket Cinema Camera 6K G2', model: 'BMPCC 6K G2', category: 'camera', aliases: ['bmd', 'bmpcc'],
    outputs: ['HDMI OUT'] },
  { brand: B, name: 'Pocket Cinema Camera 6K Pro', model: 'BMPCC 6K Pro', category: 'camera', aliases: ['bmd', 'bmpcc'],
    outputs: ['HDMI OUT'] },
  { brand: B, name: 'Cinema Camera 6K', category: 'camera', aliases: ['bmd', 'bmcc'], outputs: ['HDMI OUT'] },
  { brand: B, name: 'PYXIS 6K', category: 'camera', aliases: ['bmd'], outputs: ['12G-SDI OUT', 'HDMI OUT'] },
  { brand: B, name: 'Studio Camera 4K Plus', category: 'camera', aliases: ['bmd'], outputs: ['HDMI OUT'] },
  { brand: B, name: 'Studio Camera 4K Plus G2', category: 'camera', aliases: ['bmd'], outputs: ['HDMI OUT'] },
  { brand: B, name: 'Studio Camera 4K Pro', category: 'camera', aliases: ['bmd'],
    inputs: ['12G-SDI IN (RETURN)'], outputs: ['12G-SDI OUT', 'HDMI OUT'], ios: ['ETHERNET'] },
  { brand: B, name: 'Studio Camera 4K Pro G2', category: 'camera', aliases: ['bmd'],
    inputs: ['12G-SDI IN (RETURN)'], outputs: ['12G-SDI OUT', 'HDMI OUT'], ios: ['ETHERNET'] },
  { brand: B, name: 'Studio Camera 6K Pro', category: 'camera', aliases: ['bmd'],
    inputs: ['12G-SDI IN (RETURN)'], outputs: ['12G-SDI OUT', 'HDMI OUT'], ios: ['ETHERNET'] },
  { brand: B, name: 'Micro Studio Camera 4K G2', category: 'camera', aliases: ['bmd'],
    inputs: ['SDI IN (RETURN)'], outputs: ['SDI OUT', 'HDMI OUT'] },
  { brand: B, name: 'URSA Mini Pro 4.6K G2', category: 'camera', aliases: ['bmd', 'ursa'],
    inputs: ['12G-SDI IN (RETURN)', 'REF IN'], outputs: ['12G-SDI OUT', 'SDI MONITOR OUT'] },
  { brand: B, name: 'URSA Mini Pro 12K', category: 'camera', aliases: ['bmd', 'ursa'],
    inputs: ['12G-SDI IN (RETURN)', 'REF IN'], outputs: ['12G-SDI OUT', 'SDI MONITOR OUT'] },
  { brand: B, name: 'URSA Mini Pro 12K OLPF', category: 'camera', aliases: ['bmd', 'ursa'],
    inputs: ['12G-SDI IN (RETURN)', 'REF IN'], outputs: ['12G-SDI OUT', 'SDI MONITOR OUT'] },
  { brand: B, name: 'URSA Broadcast G2', category: 'camera', aliases: ['bmd', 'ursa'],
    inputs: ['12G-SDI IN (RETURN)', 'REF IN'], outputs: ['12G-SDI OUT', 'SDI MONITOR OUT'] },
  { brand: B, name: 'URSA Cine 12K LF', category: 'camera', aliases: ['bmd', 'ursa'],
    inputs: ['12G-SDI IN (RETURN)'], outputs: ['12G-SDI OUT 1', '12G-SDI OUT 2'], ios: ['ETHERNET 10G'] },
  { brand: B, name: 'Camera Fiber Converter', category: 'converter', aliases: ['bmd', 'smpte fiber'],
    inputs: ['SDI IN (FROM CAMERA)'], outputs: ['SDI OUT (RETURN TO CAMERA)'], ios: ['SMPTE FIBER'] },
  { brand: B, name: 'Studio Fiber Converter', category: 'converter', aliases: ['bmd', 'smpte fiber'],
    inputs: ['SDI IN (PROGRAM RETURN)', 'REF IN'], outputs: ['SDI OUT (CAMERA)'], ios: ['SMPTE FIBER', 'ETHERNET'] },

  // ── Recorders / streaming ────────────────────────────────────────────────
  // HyperDeck รุ่นเก่าตัวเทา (ก่อนซีรีส์ HD/4K Pro ปี 2021)
  { brand: B, name: 'HyperDeck Studio 12G', category: 'recorder', aliases: ['bmd', 'สีเทา', 'รุ่นเก่า'],
    inputs: ['12G-SDI IN', 'REF IN'], outputs: ['12G-SDI OUT', 'SDI MONITOR OUT', 'HDMI OUT'], ios: ['ETHERNET', 'USB'] },
  { brand: B, name: 'HyperDeck Studio Pro', category: 'recorder', aliases: ['bmd', 'สีเทา', 'รุ่นเก่า'],
    inputs: ['6G-SDI IN', 'HDMI IN', 'REF IN', 'ANALOG IN'], outputs: ['6G-SDI OUT', 'HDMI OUT', 'ANALOG OUT'], ios: ['ETHERNET', 'USB', 'THUNDERBOLT'] },
  { brand: B, name: 'HyperDeck Studio (รุ่นเก่า)', model: 'HyperDeck Studio', category: 'recorder', aliases: ['bmd', 'สีเทา', 'รุ่นเก่า'],
    inputs: ['SDI IN', 'HDMI IN', 'REF IN'], outputs: ['SDI OUT', 'HDMI OUT'], ios: ['ETHERNET', 'USB'] },
  { brand: B, name: 'HyperDeck Studio Mini', category: 'recorder', aliases: ['bmd', 'สีเทา', 'รุ่นเก่า'],
    inputs: ['6G-SDI IN', 'REF IN'], outputs: ['6G-SDI OUT', 'HDMI OUT'], ios: ['ETHERNET', 'USB'] },
  { brand: B, name: 'HyperDeck Shuttle 2', category: 'recorder', aliases: ['bmd', 'รุ่นเก่า'],
    inputs: ['SDI IN', 'HDMI IN'], outputs: ['SDI OUT', 'HDMI OUT'], ios: ['USB'] },
  { brand: B, name: 'HyperDeck Studio HD Mini', category: 'recorder', aliases: ['bmd'],
    inputs: ['SDI IN'], outputs: ['SDI OUT', 'HDMI OUT'], ios: ['ETHERNET', 'USB-C'] },
  { brand: B, name: 'HyperDeck Studio HD Plus', category: 'recorder', aliases: ['bmd'],
    inputs: ['SDI IN', 'HDMI IN'], outputs: ['SDI OUT', 'HDMI OUT'], ios: ['ETHERNET', 'USB-C'] },
  { brand: B, name: 'HyperDeck Studio HD Pro', category: 'recorder', aliases: ['bmd'],
    inputs: ['SDI IN', 'HDMI IN'], outputs: ['SDI OUT', 'HDMI OUT'], ios: ['ETHERNET', 'USB-C'] },
  { brand: B, name: 'HyperDeck Studio 4K Pro', category: 'recorder', aliases: ['bmd'],
    inputs: ['12G-SDI IN', 'HDMI IN'], outputs: ['12G-SDI OUT', 'HDMI OUT'], ios: ['ETHERNET', 'USB-C'] },
  { brand: B, name: 'HyperDeck Shuttle HD', category: 'recorder', aliases: ['bmd'],
    inputs: ['HDMI IN'], outputs: ['HDMI OUT'], ios: ['ETHERNET', 'USB-C'] },
  { brand: B, name: 'HyperDeck Extreme 8K HDR', category: 'recorder', aliases: ['bmd'],
    inputs: [...seq('12G-SDI IN', 4), 'HDMI IN'], outputs: [...seq('12G-SDI OUT', 4), 'HDMI OUT'], ios: ['ETHERNET', 'USB-C'] },
  { brand: B, name: 'HyperDeck Extreme 4K HDR', category: 'recorder', aliases: ['bmd'],
    inputs: ['12G-SDI IN', 'HDMI IN'], outputs: ['12G-SDI OUT', 'HDMI OUT'], ios: ['ETHERNET', 'USB-C'] },
  { brand: B, name: 'Video Assist 5" 12G HDR', category: 'monitor', aliases: ['bmd'],
    inputs: ['12G-SDI IN', 'HDMI IN'], outputs: ['12G-SDI OUT', 'HDMI OUT'] },
  { brand: B, name: 'Video Assist 7" 12G HDR', category: 'monitor', aliases: ['bmd'],
    inputs: ['12G-SDI IN', 'HDMI IN'], outputs: ['12G-SDI OUT', 'HDMI OUT'] },
  { brand: B, name: 'Web Presenter HD', category: 'recorder', aliases: ['bmd', 'encoder', 'stream'],
    inputs: ['SDI IN'], outputs: ['SDI LOOP OUT'], ios: ['ETHERNET', 'USB-C'] },
  { brand: B, name: 'Web Presenter 4K', category: 'recorder', aliases: ['bmd', 'encoder', 'stream'],
    inputs: ['12G-SDI IN'], outputs: ['12G-SDI LOOP OUT'], ios: ['ETHERNET', 'USB-C'] },
  { brand: B, name: 'UltraStudio 4K Mini', category: 'recorder', aliases: ['bmd', 'capture'],
    inputs: ['12G-SDI IN', 'HDMI IN'], outputs: ['12G-SDI OUT', 'HDMI OUT'], ios: ['THUNDERBOLT 3'] },
  { brand: B, name: 'Blackmagic Cloud Store 20TB', model: 'Cloud Store 20TB', category: 'network', aliases: ['bmd', 'storage'],
    ios: ['ETHERNET 10G 1', 'ETHERNET 10G 2', 'ETHERNET 10G 3', 'ETHERNET 10G 4'] },
  { brand: B, name: 'Blackmagic Cloud Store Mini', model: 'Cloud Store Mini', category: 'network', aliases: ['bmd', 'storage'],
    ios: ['ETHERNET 10G'] },
  { brand: B, name: 'Blackmagic MultiDock 10G', model: 'MultiDock 10G', category: 'network', aliases: ['bmd', 'storage'],
    ios: ['ETHERNET 10G', 'USB-C'] },

  // ── Converters ───────────────────────────────────────────────────────────
  { brand: B, name: 'Mini Converter SDI to HDMI 6G', category: 'converter', aliases: ['bmd'],
    inputs: ['SDI IN'], outputs: ['SDI LOOP', 'HDMI OUT'] },
  { brand: B, name: 'Mini Converter HDMI to SDI 6G', category: 'converter', aliases: ['bmd'],
    inputs: ['HDMI IN'], outputs: ['SDI OUT 1', 'SDI OUT 2'] },
  { brand: B, name: 'Mini Converter SDI to Audio 4K', category: 'converter', aliases: ['bmd'],
    inputs: ['SDI IN'], outputs: ['SDI LOOP', 'AUDIO OUT 1', 'AUDIO OUT 2', 'AES OUT'] },
  { brand: B, name: 'Mini Converter Audio to SDI 4K', category: 'converter', aliases: ['bmd'],
    inputs: ['SDI IN', 'AUDIO IN 1', 'AUDIO IN 2', 'AES IN'], outputs: ['SDI OUT'] },
  { brand: B, name: 'Mini Converter SDI Distribution 4K', category: 'converter', aliases: ['bmd', 'da'],
    inputs: ['SDI IN'], outputs: seq('SDI OUT', 8) },
  { brand: B, name: 'Mini Converter Optical Fiber 12G', category: 'converter', aliases: ['bmd'],
    inputs: ['SDI IN', 'OPTICAL IN'], outputs: ['SDI OUT', 'OPTICAL OUT'] },
  { brand: B, name: 'Mini Converter UpDownCross HD', category: 'converter', aliases: ['bmd'],
    inputs: ['SDI IN', 'HDMI IN'], outputs: ['SDI OUT', 'HDMI OUT'] },
  { brand: B, name: 'Micro Converter BiDirectional SDI/HDMI 3G', category: 'converter', aliases: ['bmd', 'bidirect'],
    inputs: ['SDI IN', 'HDMI IN'], outputs: ['SDI OUT', 'HDMI OUT'] },
  { brand: B, name: 'Micro Converter BiDirectional SDI/HDMI 12G', category: 'converter', aliases: ['bmd', 'bidirect'],
    inputs: ['12G-SDI IN', 'HDMI IN'], outputs: ['12G-SDI OUT', 'HDMI OUT'] },
  { brand: B, name: 'Micro Converter SDI to HDMI 3G', category: 'converter', aliases: ['bmd'],
    inputs: ['SDI IN'], outputs: ['HDMI OUT'] },
  { brand: B, name: 'Micro Converter SDI to HDMI 12G', category: 'converter', aliases: ['bmd'],
    inputs: ['12G-SDI IN'], outputs: ['HDMI OUT'] },
  { brand: B, name: 'Micro Converter HDMI to SDI 3G', category: 'converter', aliases: ['bmd'],
    inputs: ['HDMI IN'], outputs: ['SDI OUT'] },
  { brand: B, name: 'Micro Converter HDMI to SDI 12G', category: 'converter', aliases: ['bmd'],
    inputs: ['HDMI IN'], outputs: ['12G-SDI OUT'] },
  { brand: B, name: 'Teranex Mini SDI to HDMI 12G', category: 'converter', aliases: ['bmd'],
    inputs: ['12G-SDI IN'], outputs: ['12G-SDI LOOP', 'HDMI OUT'], ios: ['ETHERNET'] },
  { brand: B, name: 'Teranex Mini HDMI to SDI 12G', category: 'converter', aliases: ['bmd'],
    inputs: ['HDMI IN'], outputs: ['12G-SDI OUT 1', '12G-SDI OUT 2'], ios: ['ETHERNET'] },
  { brand: B, name: 'Teranex Mini SDI to Audio 12G', category: 'converter', aliases: ['bmd'],
    inputs: ['12G-SDI IN'], outputs: ['12G-SDI LOOP', 'ANALOG OUT 1-4', 'AES OUT 1-4'], ios: ['ETHERNET'] },
  { brand: B, name: 'Teranex Mini Audio to SDI 12G', category: 'converter', aliases: ['bmd'],
    inputs: ['12G-SDI IN', 'ANALOG IN 1-4', 'AES IN 1-4'], outputs: ['12G-SDI OUT'], ios: ['ETHERNET'] },
  { brand: B, name: 'Teranex Mini Optical to HDMI 12G', category: 'converter', aliases: ['bmd'],
    inputs: ['OPTICAL IN'], outputs: ['HDMI OUT', '12G-SDI OUT'], ios: ['ETHERNET'] },
  { brand: B, name: 'Teranex Mini 12G-SDI to Quad SDI', category: 'converter', aliases: ['bmd'],
    inputs: ['12G-SDI IN'], outputs: seq('3G-SDI OUT', 4), ios: ['ETHERNET'] },
  { brand: B, name: 'Teranex Mini Quad SDI to 12G-SDI', category: 'converter', aliases: ['bmd'],
    inputs: seq('3G-SDI IN', 4), outputs: ['12G-SDI OUT'], ios: ['ETHERNET'] },
  { brand: B, name: 'Teranex AV', category: 'converter', aliases: ['bmd'],
    inputs: ['12G-SDI IN', 'HDMI IN'], outputs: ['12G-SDI OUT', 'HDMI OUT'], ios: ['ETHERNET'] },
  { brand: B, name: 'Blackmagic 2110 IP Converter 3x3G', model: '2110 IP Converter 3x3G', category: 'converter', aliases: ['bmd', 'smpte 2110', 'ip'],
    inputs: seq('SDI IN', 3), outputs: seq('SDI OUT', 3), ios: ['ETHERNET 10G'] },
  { brand: B, name: 'Blackmagic 2110 IP Mini BiDirect 12G', model: '2110 IP Mini BiDirect 12G', category: 'converter', aliases: ['bmd', 'smpte 2110', 'ip'],
    inputs: ['12G-SDI IN'], outputs: ['12G-SDI OUT'], ios: ['ETHERNET 10G'] },
  // NAB 2025 (US$545) — แปลง format SD/HD/UHD ข้าม 12G-SDI / HDMI / 2110 · rack ⅓ U + LCD, USB หน้าเครื่องเป็น webcam ได้
  { brand: B, name: 'Blackmagic 2110 IP UpDownCross 12G', model: '2110 IP UpDownCross 12G', category: 'converter',
    aliases: ['bmd', 'smpte 2110', 'ip', 'updowncross', 'up down cross', 'standards converter', 'scaler', 'แปลง format', '12g', 'hdmi', 'rack'],
    inputs: ['12G-SDI IN', 'HDMI 2.0 IN', 'REF IN'],
    outputs: ['12G-SDI LOOP OUT', '12G-SDI OUT 1', '12G-SDI OUT 2', 'HDMI 2.0 OUT', 'USB-C (webcam)', 'HEADPHONE'],
    ios: ['ETHERNET 10G (2110)'] },
  { brand: B, name: 'Blackmagic 2110 IP Mini IP to HDMI', model: '2110 IP Mini IP to HDMI', category: 'converter', aliases: ['bmd', 'smpte 2110', 'ip'],
    outputs: ['HDMI OUT'], ios: ['ETHERNET 10G'] },

  // ── Routers ──────────────────────────────────────────────────────────────
  { brand: B, name: 'Smart Videohub 12x12', category: 'converter', aliases: ['bmd', 'router', 'videohub'],
    inputs: seq('IN', 12), outputs: seq('OUT', 12), ios: ['ETHERNET'] },
  { brand: B, name: 'Smart Videohub 20x20', category: 'converter', aliases: ['bmd', 'router', 'videohub'],
    inputs: seq('IN', 20), outputs: seq('OUT', 20), ios: ['ETHERNET'] },
  { brand: B, name: 'Smart Videohub 40x40', category: 'converter', aliases: ['bmd', 'router', 'videohub'],
    inputs: seq('IN', 40), outputs: seq('OUT', 40), ios: ['ETHERNET'] },
  { brand: B, name: 'Videohub 10x10 12G', category: 'converter', aliases: ['bmd', 'router', 'videohub'],
    inputs: seq('12G IN', 10), outputs: seq('12G OUT', 10), ios: ['ETHERNET'] },
  { brand: B, name: 'Videohub 20x20 12G', category: 'converter', aliases: ['bmd', 'router', 'videohub'],
    inputs: seq('12G IN', 20), outputs: seq('12G OUT', 20), ios: ['ETHERNET'] },
  { brand: B, name: 'Videohub 40x40 12G', category: 'converter', aliases: ['bmd', 'router', 'videohub'],
    inputs: seq('12G IN', 40), outputs: seq('12G OUT', 40), ios: ['ETHERNET'] },
  { brand: B, name: 'Videohub 80x80 12G', category: 'converter', aliases: ['bmd', 'router', 'videohub'],
    inputs: seq('12G IN', 80), outputs: seq('12G OUT', 80), ios: ['ETHERNET'] },
  { brand: B, name: 'Videohub Master Control Pro', category: 'converter', aliases: ['bmd', 'router', 'videohub', 'panel'], ios: ['ETHERNET'] },
  { brand: B, name: 'Videohub Smart Control Pro', category: 'converter', aliases: ['bmd', 'router', 'videohub', 'panel'], ios: ['ETHERNET'] },

  // ── Monitoring ───────────────────────────────────────────────────────────
  { brand: B, name: 'MultiView 4 HD', category: 'monitor', aliases: ['bmd', 'multiviewer'],
    inputs: seq('SDI IN', 4), outputs: ['SDI OUT', 'HDMI OUT'], ios: ['ETHERNET'] },
  { brand: B, name: 'MultiView 16', category: 'monitor', aliases: ['bmd', 'multiviewer'],
    inputs: seq('SDI IN', 16), outputs: ['SDI OUT', 'HDMI OUT'], ios: ['ETHERNET'] },
  { brand: B, name: 'SmartView 4K', category: 'monitor', aliases: ['bmd'],
    inputs: ['12G-SDI IN A', '12G-SDI IN B'], outputs: ['12G-SDI LOOP A', '12G-SDI LOOP B'], ios: ['ETHERNET'] },
  { brand: B, name: 'SmartView Duo 4K', category: 'monitor', aliases: ['bmd'],
    inputs: ['SDI IN 1', 'SDI IN 2'], outputs: ['SDI LOOP 1', 'SDI LOOP 2'], ios: ['ETHERNET'] },
  { brand: B, name: 'SmartScope Duo 4K', category: 'monitor', aliases: ['bmd', 'scope', 'waveform'],
    inputs: ['SDI IN 1', 'SDI IN 2'], outputs: ['SDI LOOP 1', 'SDI LOOP 2'], ios: ['ETHERNET'] },
  { brand: B, name: 'Audio Monitor 12G G3', category: 'audio', aliases: ['bmd'],
    inputs: ['12G-SDI IN', 'AES IN', 'ANALOG IN'], outputs: ['12G-SDI LOOP', 'HDMI OUT'], ios: ['ETHERNET'] },
]
